#!/usr/bin/env bash

set -eo pipefail

# shellcheck disable=SC2034
declare binding="binding.json" token="token.json"

prop() {

  local file=${!1}
  local propname=$2
  jq -r ".${propname}" "$file"

}

main() {

  local endpoint
  endpoint="${1:?Specify versioned endpoint e.g. /v1/endpoint_name}"
  endpoint="${endpoint#/}"

  curl \
    --header "Authorization: Bearer $(prop token access_token)" \
    --fail \
    --verbose \
    --location \
    --url "$(prop binding sm_url)/$endpoint"

}

main "$@"
