#!/usr/bin/env bash

# Set everything up ready for the talk

declare IDENTITY=blue
declare SUBACCOUNT=trial
declare HERE="${0%/*}"
declare ROLECOLLECTION="Cloud Connector Administrator"
declare SERVICEINSTANCE=cis-central

set -euo pipefail

main() {

  local username subaccountguid globalaccount
  declare -x CF_PASSWORD

  username="$(pass btp/$IDENTITY/user)"
  globalaccount="$(pass btp/$IDENTITY/ga)"

  # Log in with btp CLI and target the right subaccount
  btplogin "$IDENTITY"
  subaccountguid="$(btpguid --target $SUBACCOUNT)"

  # Remove the test role collection from my user
  btp unassign security/role-collection \
    "$ROLECOLLECTION" \
    --from-user "$username"

  # Set the CF API endpoint, log in and target main org
  cf api "$("$HERE/getcfapiendpoint" "$subaccountguid")"
  # shellcheck disable=SC2034
  CF_PASSWORD="$(pass btp/$IDENTITY/password)"
  cf auth "$username"
  cf target -o "$globalaccount"

  # Remove any existing CIS service instance & keys
  dsik "$SERVICEINSTANCE"

  # Remove any existing JSON files from the dir where this script is
  # shellcheck disable=SC2086
  [[ $(find $HERE -name '*.json' | wc -l) -gt 0 ]] && rm -i $HERE/*.json

  return 0

}

main "$@"
